//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace murzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class causes
    {
        public causes()
        {
            this.rasp = new HashSet<rasp>();
            this.rezhrasp = new HashSet<rezhrasp>();
        }
    
        public int arendid { get; set; }
        public string causeArend { get; set; }
    
        public virtual ICollection<rasp> rasp { get; set; }
        public virtual ICollection<rezhrasp> rezhrasp { get; set; }
    }
}
