//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace murzaev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<causes> causes { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<polzovateli> polzovateli { get; set; }
        public DbSet<rasp> rasp { get; set; }
        public DbSet<rezh> rezh { get; set; }
        public DbSet<rezhrasp> rezhrasp { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<userPhoto> userPhoto { get; set; }
        public DbSet<zal> zal { get; set; }
    }
}
