//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace murzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class polzovateli
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string login { get; set; }
        public Nullable<int> password { get; set; }
        public Nullable<bool> admin { get; set; }
    
        public virtual gender gender { get; set; }
    }
}
