//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace murzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class rasp
    {
        public int raspid { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string namecause { get; set; }
    
        public virtual causes causes { get; set; }
        public virtual rezh rezh { get; set; }
        public virtual zal zal { get; set; }
    }
}
