//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace murzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class zal
    {
        public zal()
        {
            this.rasp = new HashSet<rasp>();
        }
    
        public int placeid { get; set; }
        public string place { get; set; }
    
        public virtual ICollection<rasp> rasp { get; set; }
    }
}
